"""
Centralized test model configuration.

This module provides semantic aliases for model IDs used throughout the test suite.
Models are categorized by their capabilities and use cases to make tests more readable
and maintainable.

When a model cache exists (generated by ``pytest --refresh-models``), aliases are
populated from dynamically resolved Venice API data.  Without a cache, hardcoded
fallback defaults are used so that tests still run offline.

Usage:
    from tests.fixtures.test_models import TEST_MODELS

    # In your test
    response = await client.chat.create(
        model=TEST_MODELS.DEFAULT_TEXT_MODEL,
        messages=[...]
    )
"""

from dataclasses import dataclass, field
from typing import Any

from tests.fixtures.model_resolver import load_cache

_cache = load_cache()
_aliases = _cache["aliases"] if _cache else {}
_lists = _cache["lists"] if _cache else {}
_voices = _cache.get("voices") if _cache else None


def _a(key: str, fallback: str) -> str:
    """Resolve an alias from cache, falling back to a hardcoded default."""
    return _aliases.get(key, fallback)


def _l(key: str, fallback: list) -> list:
    """Resolve a list from cache, falling back to a hardcoded default."""
    return _lists.get(key, fallback)


@dataclass
class ModelConfig:
    """Configuration for test models with semantic aliases."""

    # ============= TEXT MODELS =============
    # Default models for general testing
    DEFAULT_TEXT_MODEL: str = _a("DEFAULT_TEXT_MODEL", "llama-3.3-70b")
    DEFAULT_TEXT_MODEL_ID: str = DEFAULT_TEXT_MODEL

    # Small/fast models for quick tests
    SMALL_TEXT_MODEL: str = _a("SMALL_TEXT_MODEL", "qwen3-4b")
    SMALL_TEXT_MODEL_ID: str = SMALL_TEXT_MODEL
    FASTEST_TEXT_MODEL: str = _a("FASTEST_TEXT_MODEL", "llama-3.2-3b")
    FASTEST_TEXT_MODEL_ID: str = FASTEST_TEXT_MODEL

    # Medium models
    MEDIUM_TEXT_MODEL: str = _a("MEDIUM_TEXT_MODEL", "mistral-31-24b")
    MEDIUM_TEXT_MODEL_ID: str = MEDIUM_TEXT_MODEL
    MEDIUM_BETA_MODEL: str = _a("MEDIUM_BETA_MODEL", "mistral-32-24b")

    # Large models for intelligence tests
    LARGE_TEXT_MODEL: str = _a("LARGE_TEXT_MODEL", "qwen3-235b")
    LARGE_TEXT_MODEL_ID: str = LARGE_TEXT_MODEL
    MOST_INTELLIGENT_MODEL: str = _a("MOST_INTELLIGENT_MODEL", "llama-3.1-405b")

    # Specialized text models
    UNCENSORED_MODEL: str = _a("UNCENSORED_MODEL", "venice-uncensored")
    UNCENSORED_MODEL_ID: str = UNCENSORED_MODEL
    MOST_UNCENSORED_MODEL: str = _a("MOST_UNCENSORED_MODEL", "dolphin-2.9.2-qwen2-72b")
    UNCENSORED_LARGE_MODEL: str = _a("UNCENSORED_LARGE_MODEL", "qwen3-235b-dolphin")

    # Reasoning models
    REASONING_MODEL: str = _a("REASONING_MODEL", "qwen-2.5-qwq-32b")
    REASONING_MODEL_ID: str = REASONING_MODEL
    DEFAULT_REASONING_MODEL: str = _a("DEFAULT_REASONING_MODEL", "deepseek-r1-671b")

    # Code models
    CODE_MODEL: str = _a("CODE_MODEL", "qwen-2.5-coder-32b")
    CODE_MODEL_ID: str = CODE_MODEL
    DEFAULT_CODE_MODEL: str = _a("DEFAULT_CODE_MODEL", "qwen-2.5-coder-32b")
    CODE_LITE_MODEL: str = _a("CODE_LITE_MODEL", "deepseek-coder-v2-lite")

    # Vision models
    VISION_MODEL: str = _a("VISION_MODEL", "mistral-31-24b")
    VISION_MODEL_ID: str = VISION_MODEL
    DEFAULT_VISION_MODEL: str = _a("DEFAULT_VISION_MODEL", "mistral-31-24b")
    VISION_72B_MODEL: str = _a("VISION_72B_MODEL", "qwen-2.5-vl")

    # Models with specific capabilities
    FUNCTION_CALLING_MODEL: str = _a("FUNCTION_CALLING_MODEL", "llama-3.3-70b")
    WEB_SEARCH_MODEL: str = _a("WEB_SEARCH_MODEL", "venice-uncensored")
    RESPONSE_SCHEMA_MODEL: str = _a("RESPONSE_SCHEMA_MODEL", "qwen3-4b")
    LOG_PROBS_MODEL: str = _a("LOG_PROBS_MODEL", "llama-3.2-3b")

    # ============= IMAGE MODELS =============
    DEFAULT_IMAGE_MODEL: str = _a("DEFAULT_IMAGE_MODEL", "venice-sd35")
    DEFAULT_IMAGE_MODEL_ID: str = DEFAULT_IMAGE_MODEL

    HIGHEST_QUALITY_IMAGE_MODEL: str = _a("HIGHEST_QUALITY_IMAGE_MODEL", "flux-dev")
    CUSTOM_IMAGE_MODEL: str = _a("CUSTOM_IMAGE_MODEL", "flux-dev-uncensored")
    UNCENSORED_IMAGE_MODEL: str = _a("UNCENSORED_IMAGE_MODEL", "pony-realism")
    ANIME_IMAGE_MODEL: str = _a("ANIME_IMAGE_MODEL", "wai-Illustrious")

    # Alternative image models
    HIDREAM_MODEL: str = _a("HIDREAM_MODEL", "hidream")
    LUSTIFY_MODEL: str = _a("LUSTIFY_MODEL", "lustify-sdxl")
    QWEN_IMAGE_MODEL: str = _a("QWEN_IMAGE_MODEL", "qwen-image")
    SD35_MODEL: str = _a("SD35_MODEL", "stable-diffusion-3.5")

    # ============= EMBEDDING MODELS =============
    EMBEDDING_MODEL: str = _a("EMBEDDING_MODEL", "text-embedding-bge-m3")
    EMBEDDING_MODEL_ID: str = EMBEDDING_MODEL
    DEFAULT_EMBEDDING_MODEL: str = EMBEDDING_MODEL

    # ============= AUDIO/TTS MODELS =============
    TTS_MODEL: str = _a("TTS_MODEL", "tts-kokoro")
    TTS_MODEL_ID: str = TTS_MODEL
    DEFAULT_TTS_MODEL: str = TTS_MODEL

    # Voice IDs for TTS
    VOICE_ID_FEMALE: str = "af_bella"
    VOICE_ID_MALE: str = "am_adam"
    VOICE_ID: str = VOICE_ID_FEMALE
    DEFAULT_VOICE_ID: str = VOICE_ID

    # All available voices for testing variety
    TTS_VOICES: list = field(
        default_factory=lambda: (
            _voices
            if _voices
            else [
                "af_alloy",
                "af_aoede",
                "af_bella",
                "af_heart",
                "af_jadzia",
                "am_adam",
                "am_echo",
                "am_eric",
                "am_fenrir",
                "am_liam",
            ]
        )
    )

    # ============= UTILITY MODELS =============
    UPSCALER_MODEL: str = _a("UPSCALER_MODEL", "upscaler")
    UPSCALER_MODEL_ID: str = UPSCALER_MODEL

    INPAINT_MODEL: str = _a("INPAINT_MODEL", "edit-image")
    INPAINT_MODEL_ID: str = INPAINT_MODEL
    INPAINT_BETA_MODEL: str = _a("INPAINT_BETA_MODEL", "qwen-edit")

    # ============= MODEL CATEGORIES =============
    CHEAP_TEXT_MODELS: list = field(
        default_factory=lambda: _l("CHEAP_TEXT_MODELS", ["qwen3-4b", "llama-3.2-3b"])
    )
    EXPENSIVE_TEXT_MODELS: list = field(
        default_factory=lambda: _l(
            "EXPENSIVE_TEXT_MODELS",
            ["qwen3-235b", "llama-3.1-405b", "deepseek-r1-671b"],
        )
    )

    BETA_MODELS: list = field(
        default_factory=lambda: _l(
            "BETA_MODELS",
            ["mistral-32-24b", "qwen3-235b-dolphin", "qwen-edit"],
        )
    )

    FUNCTION_CALLING_MODELS: list = field(
        default_factory=lambda: _l(
            "FUNCTION_CALLING_MODELS",
            [
                "qwen3-4b",
                "mistral-31-24b",
                "mistral-32-24b",
                "qwen3-235b",
                "llama-3.2-3b",
                "llama-3.3-70b",
            ],
        )
    )

    VISION_CAPABLE_MODELS: list = field(
        default_factory=lambda: _l(
            "VISION_CAPABLE_MODELS",
            ["mistral-31-24b", "mistral-32-24b", "qwen-2.5-vl"],
        )
    )

    ALL_IMAGE_MODELS: list = field(
        default_factory=lambda: _l(
            "ALL_IMAGE_MODELS",
            [
                "venice-sd35",
                "hidream",
                "flux-dev",
                "flux-dev-uncensored",
                "lustify-sdxl",
                "pony-realism",
                "qwen-image",
                "stable-diffusion-3.5",
                "wai-Illustrious",
            ],
        )
    )


# Create singleton instance
TEST_MODELS = ModelConfig()


# Model metadata for advanced testing
# When a cache is available, this is populated from live API data
_cached_metadata = _cache.get("metadata") if _cache else None

MODEL_METADATA: dict[str, dict[str, Any]] = (
    _cached_metadata
    if _cached_metadata
    else {
        "llama-3.3-70b": {
            "context_tokens": 65536,
            "supports_function_calling": True,
            "supports_vision": False,
            "supports_web_search": True,
            "quantization": "fp8",
            "pricing_tier": "medium",
        },
        "qwen3-4b": {
            "context_tokens": 40960,
            "supports_function_calling": True,
            "supports_vision": False,
            "supports_web_search": True,
            "quantization": "fp8",
            "pricing_tier": "cheap",
        },
        "llama-3.2-3b": {
            "context_tokens": 131072,
            "supports_function_calling": True,
            "supports_vision": False,
            "supports_web_search": True,
            "quantization": "fp16",
            "pricing_tier": "cheap",
        },
        "venice-sd35": {
            "type": "image",
            "steps_default": 25,
            "steps_max": 30,
            "prompt_char_limit": 1500,
            "pricing_tier": "standard",
        },
        "flux-dev": {
            "type": "image",
            "steps_default": 25,
            "steps_max": 30,
            "prompt_char_limit": 2048,
            "pricing_tier": "standard",
        },
        "tts-kokoro": {"type": "tts", "voices_count": 56, "pricing_tier": "expensive"},
    }
)


def get_model_for_capability(capability: str) -> str:
    """
    Get an appropriate model for a specific capability.

    Args:
        capability: The required capability (e.g., "vision", "function_calling", "reasoning")

    Returns:
        Model ID that supports the capability
    """
    capability_map = {
        "vision": TEST_MODELS.DEFAULT_VISION_MODEL,
        "function_calling": TEST_MODELS.FUNCTION_CALLING_MODEL,
        "reasoning": TEST_MODELS.DEFAULT_REASONING_MODEL,
        "code": TEST_MODELS.DEFAULT_CODE_MODEL,
        "uncensored": TEST_MODELS.MOST_UNCENSORED_MODEL,
        "web_search": TEST_MODELS.WEB_SEARCH_MODEL,
        "response_schema": TEST_MODELS.RESPONSE_SCHEMA_MODEL,
        "log_probs": TEST_MODELS.LOG_PROBS_MODEL,
        "embedding": TEST_MODELS.DEFAULT_EMBEDDING_MODEL,
        "image": TEST_MODELS.DEFAULT_IMAGE_MODEL,
        "tts": TEST_MODELS.DEFAULT_TTS_MODEL,
        "upscale": TEST_MODELS.UPSCALER_MODEL,
        "inpaint": TEST_MODELS.INPAINT_MODEL,
    }
    return capability_map.get(capability, TEST_MODELS.DEFAULT_TEXT_MODEL)


def get_test_model_by_price(price_tier: str = "cheap") -> str:
    """
    Get a model based on pricing tier for cost-sensitive tests.

    Args:
        price_tier: "cheap", "medium", or "expensive"

    Returns:
        Model ID for the requested price tier
    """
    price_map = {
        "cheap": TEST_MODELS.SMALL_TEXT_MODEL,
        "medium": TEST_MODELS.DEFAULT_TEXT_MODEL,
        "expensive": TEST_MODELS.LARGE_TEXT_MODEL,
    }
    return price_map.get(price_tier, TEST_MODELS.SMALL_TEXT_MODEL)


# Export all for easy importing
__all__ = [
    "TEST_MODELS",
    "MODEL_METADATA",
    "get_model_for_capability",
    "get_test_model_by_price",
]
