import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guidesSidebar: [
    'getting-started',
    {type: 'category', label: 'Guides', collapsed: false, items: [{type: 'autogenerated', dirName: 'guides'}]},
  ],
  apiSidebar: ['api-reference', {type: 'autogenerated', dirName: 'api'}],
};

export default sidebars;
